# Site Settings
title:              Joe's Website
author:             Xu GuanZhou - "Joe"
email:              gxu2@crimson.ua.edu
description:        "One stop shop to know the man as Joe"
keywords:           "resume,profolio,blog,contact"

# Handling Reading
exclude:            ['README.md', 'LICENSE.md']

# Conversion
markdown:           kramdown
kramdown:
    input:          GFM
highlighter:        rouge

# Serving
url:                ""
baseurl:            ""

# Outputting
permalink:          /:title/

# Resume settings
resume_name:                    "Homer J. Simpson"
resume_title:                   "Nuclear Safety Inspector"
resume_contact_email:           "homerjsimpson@youremailaddress.com"
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"
resume_header_contact_info: "742 Evergreen Terrace, Springfield | 555-7334 | homerjsimpson@youremailaddress.com"
resume_header_intro: "<p>This is the executive summary. You should write a few brief, concise, and meaningful sentences about yourself from a professional context, and your immediate career goals. Make the length appropriate for your needs, but K.I.S.S.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# My social media links (URL)
resume_social_links:
  resume_github_url:            "insert your URL here"
  resume_twitter_url:           "insert your URL here"
  resume_dribbble_url:          "insert your URL here"
  resume_facebook_url:          "insert your URL here"
  resume_linkedin_url:          "insert your URL here"
  resume_instagram_url:         "insert your URL here"
  resume_website_url:           "http://xuguanzhou.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
