# Site Settings
title:              Joe's Website
author:             Xu GuanZhou - "Joe"
email:              gxu2@crimson.ua.edu
description:        "One stop shop to know the man as Joe"
keywords:           "resume,profolio,blog,contact"

# Handling Reading
exclude:            ['README.md', 'LICENSE.md']

# Conversion
markdown:           kramdown
kramdown:
    input:          GFM
highlighter:        rouge

# Serving
url:                ""
baseurl:            ""

# Outputting
permalink:          /:title/

# My social media links (URL)
resume_social_links:
  resume_github_url:            "insert your URL here"
  resume_twitter_url:           "insert your URL here"
  resume_dribbble_url:          "insert your URL here"
  resume_facebook_url:          "insert your URL here"
  resume_linkedin_url:          "insert your URL here"
  resume_instagram_url:         "insert your URL here"
  resume_website_url:           "http://xuguanzhou.io"
resume_print_social_links:      true
